---
title: "ER-Golgi localisation"
output: pdf_document
---

# Setup
```{r setup}
knitr::opts_chunk$set(echo = TRUE, dev = 'png', message = FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80))
knitr::opts_chunk$set(fig.path = "../figures/")

source('../style/thesis_setup.R')

library(dplyr)
library(stringr)
library(ggplot2)
library(ggpubr)
library(rstatix)
library(readbitmap)
library(patchwork)

```

#Read in CSVs
```{r}
#maximum intensity quantification

max_dir = c('C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC97-98_analysis_temp\\max_intensity_quantification',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC105-110_analysis_temp\\MAX_fluorescence_quantification',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC111_timepoints_analysis\\MAX_fluorescence_quantification',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC68_DIV15',#SLC38A1 corrections
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC97_DIV15',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC105_DIV3',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC108_DIV15',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC113_DIV3',
            'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\CNC116_DIV3')


ptdn_max_dir = c('C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC84-100-101_Ptdn_analysis_temp\\max_intensity_quantification',
                 'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC113_Ptdn_analysis\\MAX_fluorescence_quantification',
                 'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC114_Ptdn_analysis\\MAX_fluorescence_quantification',
                 'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\CNC112_Ptdn_analysis_SLC38A1\\MAX_fluorescence_quantification')

i3_max_dir = c('C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\i3-10_analysis\\MAX_fluorescence_quantification',
               'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\i3-11-12_analysis\\MAX_fluorescence_quantification',
               'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\Localisation_analysis\\SLC38A1_corrections_analysis\\MAX_fluorescence_quantification\\i3-10')


#pull CSVs only
pull_result_csvs <- function (dir){
  return(list.files(dir, pattern = "\\_Results\\.csv$", full.names = TRUE))
}

max.csvs = pull_result_csvs(max_dir)
ptdn_max.csvs = pull_result_csvs(ptdn_max_dir)
i3_max.csvs = pull_result_csvs(i3_max_dir)


read_fluor_data <- function(csv_list, batch, cell_type){
  data = do.call(bind_rows, lapply(csv_list, function(c){#bind_rows instead of rbind to handle varying columns
    df = read.csv(c, stringsAsFactors = F)
    df$file = rep_len(c, nrow(df))
    df$batch = rep_len(batch, nrow(df))
    df$cell_type = rep_len(cell_type, nrow(df))
    return(df)
    
  }))
  
  return (data)
}

#read data
#TODO - find a neater way to do this


max.data = bind_rows(read_fluor_data(max.csvs[grepl("CNC97-98", max.csvs)], batch = "CNC97-98", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC105-110", max.csvs)], batch = "CNC105-110", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC111", max.csvs)], batch = "CNC111", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC68", max.csvs)], batch = "CNC68", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC97_", max.csvs)], batch = "CNC97", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC105", max.csvs)], batch = "CNC105", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC108", max.csvs)], batch = "CNC108", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC113", max.csvs)], batch = "CNC113", cell_type = "rat cortical"),
                 read_fluor_data(max.csvs[grepl("CNC116", max.csvs)], batch = "CNC116", cell_type = "rat cortical"))


ptdn_max.data = bind_rows(read_fluor_data(ptdn_max.csvs[grepl("CNC84-100-101", ptdn_max.csvs)], batch = "CNC84-100-101", cell_type = "rat cortical"),#TODO - SLC38A1 correction
                          read_fluor_data(ptdn_max.csvs[grepl("CNC113", ptdn_max.csvs)], batch = "CNC113", cell_type = "rat cortical"),
                          read_fluor_data(ptdn_max.csvs[grepl("CNC112", ptdn_max.csvs)], batch = "CNC112", cell_type = "rat cortical"),
                          read_fluor_data(ptdn_max.csvs[grepl("CNC114", ptdn_max.csvs)], batch = "CNC114", cell_type = "rat cortical"))

i3_max.data = read_fluor_data(i3_max.csvs, batch = '', cell_type = "i3")#extra columns with dot dendrites


```

```{r}
#condition parsing
#TODO - function?


max.data = do.call(rbind, lapply(1:nrow(max.data), function(i){
  row = max.data[i,]
  filename = last(strsplit(row$file, "/", fixed = T)[[1]])
  
  #file name format condition_age_cellno_part
  row$cond = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][1]
  row$age = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][2]
  row$transf = ifelse(row$age == "DIV3", "untransfected", "dGFP")
  row$cell_no = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][3]
  row$part = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][4]
  
  #parse result row labels
  row$measure = str_match(row$Label, ":([A-Za-z\ \\d]+):")[2]
  
  return(row)
  
}))



ptdn_max.data = do.call(rbind, lapply(1:nrow(ptdn_max.data), function(i){
  row = ptdn_max.data[i,]
  filename = last(strsplit(row$file, "/", fixed = T)[[1]])
  
  #file name format condition_age_cellno_part
  row$cond = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][1]
  row$age = "DIV15"
  row$transf = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][2]
  row$cell_no = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][3]
  row$part = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][4]
  
  #parse result row labels
  row$measure = str_match(row$Label, ":([A-Za-z\ \\d]+):")[2]
  
  return(row)
  
}))

i3_max.data = do.call(rbind, lapply(1:nrow(i3_max.data), function(i){
  row = i3_max.data[i,]
  filename = last(strsplit(row$file, "/", fixed = T)[[1]])
  
  #file name format batch_condition_age_cellno_part
  row$batch = str_match_all(filename, "([-A-Za-z\\d]+)")[[1]][1]
  row$cond = str_match_all(filename, "([-A-Za-z\\d]+)")[[1]][2]
  row$age = "DIV1"
  row$transf = "untranfected"
  row$cell_no = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][3]
  row$part = str_match_all(filename, "[-A-Za-z\\d]+")[[1]][4]
  
  #parse result row labels
  row$measure = str_match(row$Label, ":([A-Za-z\ \\d]+):")[2]
  
  return(row)
  
}))



#unique cell IDs for processing
max.data$cell_id = paste0(max.data$batch, "_", max.data$cond, "_", max.data$age,"_", max.data$transf, "_", max.data$cell_no)
ptdn_max.data$cell_id = paste0(ptdn_max.data$batch, "_", ptdn_max.data$cond, "_", ptdn_max.data$age,"_", ptdn_max.data$transf, "_", ptdn_max.data$cell_no)
i3_max.data$cell_id = paste0(i3_max.data$batch, "_", i3_max.data$cond, "_", i3_max.data$age,"_", i3_max.data$transf, "_", i3_max.data$cell_no)

```

Background correction, trimming, etc.
```{r}

#TODO - CONVERT MISSING/POINT DENDRITES (LENGTH = 0) TO NA OR DELETE

#FACTORS - all in one place
transf.levels = c('GFP', 'WT', 'Mut2', 'untransfected', 'dGFP')
transf.labels = c('Control', 'WT', 'Active', '-', 'dGFP')

age.levels = c('DIV1', 'DIV3', 'DIV15')
age.labels = c('DIV1', 'DIV3', 'DIV15')

measure.levels = c('growth cone', 'cytoplasm')
measure.labels = c('axon terminal', 'soma')

cell_type.levels = c('i3', 'rat cortical')
cell_type.labels = c('i3', 'rat cortical')

cond.levels = c('BCAP31', 'BCAP31-biotin', 'SURF4', 'ERGIC53', 'SLC38A1')
cond.labels = c('if youre reading this I coded it wrong', 'BCAP31', 'SURF4', 'ERGIC53', 'SLC38A1')

#start with cytoplasm rows
max.gc_cyto = max.data[max.data$measure == 'cytoplasm', c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
#add GC rows with bg subtracted
temp.df = max.data[max.data$measure %in% c('growth cone', 'growth cone background'), c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
temp.df.gc = do.call(rbind, lapply(unique(temp.df$cell_id), function(c){ 
    section = temp.df[temp.df$cell_id == c,]
    gc_row <- section[section$measure == 'growth cone',][1,]
    bg_row <- section[section$measure == 'growth cone background',][1,]
    #TODO - check if too many
    new_row <- data.frame(Area = gc_row$Area,
                         Mean = gc_row$Mean - bg_row$Mean,
                         IntDen = gc_row$IntDen - bg_row$IntDen,
                         RawIntDen = gc_row$RawIntDen - bg_row$RawIntDen,
                         batch = gc_row$batch,
                         cond = gc_row$cond,
                         age = gc_row$age,
                         transf = gc_row$transf,
                         measure = gc_row$measure,
                         cell_type = gc_row$cell_type,
                         cell_id = gc_row$cell_id)
    return(new_row)
  }))
  
max.gc_cyto = rbind(max.gc_cyto, temp.df.gc)
max.gc_cyto$age = factor(max.gc_cyto$age, levels = age.levels, labels = age.labels)
max.gc_cyto$transf = factor(max.gc_cyto$transf, levels = transf.levels, labels = transf.labels)
max.gc_cyto$cell_type = factor(max.gc_cyto$cell_type, levels = cell_type.levels, labels = cell_type.labels)

max.gc_cyto = max.gc_cyto[max.gc_cyto$cond != 'BCAP31',]
max.gc_cyto$cond = factor(max.gc_cyto$cond, levels = cond.levels, labels = cond.labels)


max.gc_cyto.ratio = do.call(rbind, lapply(unique(max.gc_cyto$cell_id), function(c){
  cyto_row <- max.gc_cyto[max.gc_cyto$cell_id == c & max.gc_cyto$measure == 'cytoplasm',][1,]
  gc_row <- max.gc_cyto[max.gc_cyto$cell_id == c & max.gc_cyto$measure == 'growth cone',][1,]
  new_row <- data.frame(ratio = gc_row$IntDen/cyto_row$IntDen,
                        ratio_mean = gc_row$Mean/cyto_row$Mean,
                        batch = cyto_row$batch,#this and following should always be the same between rows
                        cond = cyto_row$cond,
                        age = cyto_row$age,
                        transf = cyto_row$transf,
                        cell_type = cyto_row$cell_type,
                        cell_id = cyto_row$cell_id)
  return(new_row)
}))
max.gc_cyto.ratio = na.omit(max.gc_cyto.ratio)

max.gc_cyto.ratio$age = factor(max.gc_cyto.ratio$age, levels = age.levels, labels = age.labels)
max.gc_cyto.ratio$transf = factor(max.gc_cyto.ratio$transf, levels = transf.levels, labels = transf.labels)

max.gc_cyto$measure = factor(max.gc_cyto$measure, levels = measure.levels, labels = measure.labels)



#PROTRUDIN
#start with cytoplasm rows
ptdn_max.gc_cyto = ptdn_max.data[ptdn_max.data$measure == 'cytoplasm', c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
#add GC rows with bg subtracted
ptdn_temp.df = ptdn_max.data[ptdn_max.data$measure %in% c('growth cone', 'growth cone background'), c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
ptdn_temp.df.gc = do.call(rbind, lapply(unique(ptdn_temp.df$cell_id), function(c){ 
    section = ptdn_temp.df[ptdn_temp.df$cell_id == c,]
    gc_row <- section[section$measure == 'growth cone',][1,]
    bg_row <- section[section$measure == 'growth cone background',][1,]
    #TODO - check if too many
    new_row <- data.frame(Area = gc_row$Area,
                         Mean = gc_row$Mean - bg_row$Mean,
                         IntDen = gc_row$IntDen - bg_row$IntDen,
                         RawIntDen = gc_row$RawIntDen - bg_row$RawIntDen,
                         batch = gc_row$batch,
                         cond = gc_row$cond,
                         age = gc_row$age,
                         transf = gc_row$transf,
                         measure = gc_row$measure,
                         cell_type = gc_row$cell_type,
                         cell_id = gc_row$cell_id)
    return(new_row)
  }))
  
ptdn_max.gc_cyto = rbind(ptdn_max.gc_cyto, ptdn_temp.df.gc)
ptdn_max.gc_cyto$age = factor(ptdn_max.gc_cyto$age, levels = age.levels, labels = age.labels)
ptdn_max.gc_cyto$transf = factor(ptdn_max.gc_cyto$transf, levels = transf.levels, labels = transf.labels)
ptdn_max.gc_cyto$cell_type = factor(ptdn_max.gc_cyto$cell_type, levels = cell_type.levels, labels = cell_type.labels)

ptdn_max.gc_cyto = ptdn_max.gc_cyto[ptdn_max.gc_cyto$cond != 'BCAP31',]
ptdn_max.gc_cyto$cond = factor(ptdn_max.gc_cyto$cond, levels = cond.levels, labels = cond.labels)


ptdn_max.gc_cyto.ratio = do.call(rbind, lapply(unique(ptdn_max.gc_cyto$cell_id), function(c){
  cyto_row <- ptdn_max.gc_cyto[ptdn_max.gc_cyto$cell_id == c & ptdn_max.gc_cyto$measure == 'cytoplasm',][1,]
  gc_row <- ptdn_max.gc_cyto[ptdn_max.gc_cyto$cell_id == c & ptdn_max.gc_cyto$measure == 'growth cone',][1,]
  new_row <- data.frame(ratio = gc_row$IntDen/cyto_row$IntDen,
                        ratio_mean = gc_row$Mean/cyto_row$Mean,
                        batch = cyto_row$batch,#this and following should always be the same between rows
                        cond = cyto_row$cond,
                        age = cyto_row$age,
                        transf = cyto_row$transf,
                        cell_type = cyto_row$cell_type,
                        cell_id = cyto_row$cell_id)
  return(new_row)
}))
ptdn_max.gc_cyto.ratio = na.omit(ptdn_max.gc_cyto.ratio)

ptdn_max.gc_cyto.ratio$age = factor(ptdn_max.gc_cyto.ratio$age, levels = age.levels, labels = age.labels)

ptdn_max.gc_cyto$measure = factor(ptdn_max.gc_cyto$measure, levels = measure.levels, labels = measure.labels)









#start with cytoplasm rows
i3_max.gc_cyto = i3_max.data[i3_max.data$measure == 'cytoplasm', c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
#add GC rows with bg subtracted
i3_temp.df = i3_max.data[i3_max.data$measure %in% c('growth cone', 'growth cone background'), c('Area', 'Mean', 'IntDen', 'RawIntDen', 'batch', 'cond', 'age', 'transf', 'measure', 'cell_type', 'cell_id')]
i3_temp.df.gc = do.call(rbind, lapply(unique(i3_temp.df$cell_id), function(c){ 
    section = i3_temp.df[i3_temp.df$cell_id == c,]
    gc_row <- section[section$measure == 'growth cone',][1,]
    bg_row <- section[section$measure == 'growth cone background',][1,]
    #TODO - check if too many
    new_row <- data.frame(Area = gc_row$Area,
                         Mean = gc_row$Mean - bg_row$Mean,
                         IntDen = gc_row$IntDen - bg_row$IntDen,
                         RawIntDen = gc_row$RawIntDen - bg_row$RawIntDen,
                         batch = gc_row$batch,
                         cond = gc_row$cond,
                         age = 'DIV1',
                         transf = 'untransf',
                         measure = gc_row$measure,
                         cell_type = gc_row$cell_type,
                         cell_id = gc_row$cell_id)
    return(new_row)
  }))
  
i3_max.gc_cyto = rbind(i3_max.gc_cyto, i3_temp.df.gc)
#i3_max.gc_cyto$age = factor(i3_max.gc_cyto$age, levels = age.levels, labels = age.labels)
i3_max.gc_cyto$transf = factor(i3_max.gc_cyto$transf, levels = transf.levels, labels = transf.labels)
i3_max.gc_cyto$cell_type = factor(i3_max.gc_cyto$cell_type, levels = cell_type.levels, labels = cell_type.labels)

i3_max.gc_cyto = i3_max.gc_cyto[i3_max.gc_cyto$cond != 'BCAP31',]
i3_max.gc_cyto$cond = factor(i3_max.gc_cyto$cond, levels = cond.levels, labels = cond.labels)


i3_max.gc_cyto.ratio = do.call(rbind, lapply(unique(i3_max.gc_cyto$cell_id), function(c){
  cyto_row <- i3_max.gc_cyto[i3_max.gc_cyto$cell_id == c & i3_max.gc_cyto$measure == 'cytoplasm',][1,]
  gc_row <- i3_max.gc_cyto[i3_max.gc_cyto$cell_id == c & i3_max.gc_cyto$measure == 'growth cone',][1,]
  new_row <- data.frame(ratio = gc_row$IntDen/cyto_row$IntDen,
                        ratio_mean = gc_row$Mean/cyto_row$Mean,
                        batch = cyto_row$batch,#this and following should always be the same between rows
                        cond = cyto_row$cond,
                        age = 'DIV1',
                        transf = 'untransf',
                        cell_type = 'i3',
                        cell_id = cyto_row$cell_id)
  return(new_row)
}))
i3_max.gc_cyto.ratio = na.omit(i3_max.gc_cyto.ratio)

#i3_max.gc_cyto.ratio$age = factor(i3_max.gc_cyto.ratio$age, levels = age.levels, labels = age.labels)
i3_max.gc_cyto.ratio$transf = factor(i3_max.gc_cyto.ratio$transf, levels = transf.levels, labels = transf.labels)







```










## Plots

Max intensity - GC/soma (cytoplasm) ratio at DIV3 vs DIV15
```{r max_ratio_plot, fig.width = 16, fig.height = 4}
max_ratio_plot = ggplot(max.gc_cyto.ratio, aes(x = age, y = ratio_mean)) + 
  geom_dotplot(aes(fill = age, colour = age), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +#change colour?
  facet_wrap(~cond, ncol = 4) + 
  labs(x = '', y = 'Axon terminal:soma intensity ratio') + 
  d_format + report_theme +
  stat_compare_means(paired = F, label.y = max(max.gc_cyto.ratio$ratio_mean) + 0.1)

max_ratio_plot
```

```{r ptdn_max_ratio_plot, fig.width = 16, fig.height = 4}
#ERGIC significant - post-hoc test
ptdn_ratio_test <- ptdn_max.gc_cyto.ratio %>% group_by(cond) %>% dplyr::select(ratio_mean, transf)
ptdn_max.gc_cyto.ratio.dunn = dunn_test(ptdn_ratio_test, ratio_mean ~ transf, p.adjust.method = 'bonferroni')
ptdn_max.gc_cyto.ratio.dunn = add_xy_position(ptdn_max.gc_cyto.ratio.dunn, x = 'transf')
ptdn_max.gc_cyto.ratio.dunn = add_y_position(ptdn_max.gc_cyto.ratio.dunn, step.increase = 0.1)
ptdn_max.gc_cyto.ratio.dunn$p.adj.rounded = sapply(ptdn_max.gc_cyto.ratio.dunn$p.adj, function(p){round(p, digits = 3)})

ptdn_ratio.plotlist = lapply(cond.labels, function(l){ggplot(ptdn_max.gc_cyto.ratio[ptdn_max.gc_cyto.ratio$cond == l,], aes(x = transf, y = ratio_mean)) + 
  geom_dotplot(aes(color = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
  geom_boxplot(alpha = 0, colour = "black", position = position_dodge(width = 0.9), width = 0.5) +
  labs(x = '', y = 'Axon terminal:soma intensity ratio') + 
  ylim(-0.1, 1.4) +
  report_theme + d_format +
  stat_compare_means() + stat_pvalue_manual(ptdn_max.gc_cyto.ratio.dunn[ptdn_max.gc_cyto.ratio.dunn$cond == l,], hide.ns = TRUE, label = 'p.adj.rounded')})
names(ptdn_ratio.plotlist) = cond.labels

# ptdn_max_ratio_plot = ggplot(ptdn_max.gc_cyto.ratio, aes(x = transf, y = ratio_mean, group = transf)) + 
#   geom_dotplot(aes(color = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
#   geom_boxplot(alpha = 0, colour = "black", position = position_dodge(width = 0.9), width = 0.5) +
#   facet_wrap(~cond, ncol = 4) + 
#   labs(x = '', y = 'Axon terminal:soma intensity ratio') + 
#   ylim(-0.1, 1.4) +
#   report_theme + d_format +
#   stat_compare_means() + stat_pvalue_manual(ptdn_max.gc_cyto.ratio.dunn, hide.ns = TRUE, label = 'p.adj.rounded')
#   
# ptdn_max_ratio_plot


```








Max - GC intensity
```{r max_GC_plot, fig.width = 16, fig.height = 4}

max_GC_plot = ggplot(max.gc_cyto[max.gc_cyto$measure == 'axon terminal',], aes(x = age, y = Mean)) + 
  geom_dotplot(aes(fill = age, colour = age), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) + #change colour?
  facet_wrap(~cond, scale = 'free_y', ncol = 4) + 
  labs(x = '', y = 'Axon terminal average intensity') + 
  report_theme + d_format +
  stat_compare_means(paired = F, position = position_nudge(y = 1.5))

max_GC_plot
```
```{r ptdn_max_GC_plot, fig.height = 4, fig.width = 16}
#ERGIC, SURF4 significant - post-hoc test
ptdn_test.at <- ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'axon terminal',] %>% group_by(cond, measure) %>% dplyr::select(Mean, transf)
ptdn_max.gc_cyto.at.dunn = dunn_test(ptdn_test.at, Mean ~ transf, p.adjust.method = 'bonferroni')
ptdn_max.gc_cyto.at.dunn = add_xy_position(ptdn_max.gc_cyto.at.dunn, x = 'transf')
ptdn_max.gc_cyto.at.dunn$p.adj.rounded = sapply(ptdn_max.gc_cyto.at.dunn$p.adj, function(p){round(p, digits = 3)})


ptdn_GC.plotlist = lapply(cond.labels, function(l){ggplot(ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'axon terminal' & ptdn_max.gc_cyto$cond == l,], aes(x = transf, y = Mean)) + 
  geom_dotplot(aes(colour = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge") + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
  labs(x = '', y = 'Axon terminal average intensity') + 
  report_theme + d_format +
  stat_compare_means(position = position_nudge(y = 5)) + stat_pvalue_manual(ptdn_max.gc_cyto.at.dunn[ptdn_max.gc_cyto.at.dunn$cond == l,], hide.ns = TRUE, label = 'p.adj.rounded', position = position_nudge(y = -2))})
names(ptdn_GC.plotlist) = cond.labels

# ptdn_max_GC_plot = ggplot(ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'axon terminal',], aes(x = transf, y = Mean)) + 
#   geom_dotplot(aes(colour = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge") + 
#   geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
#   facet_wrap(~cond, scales = 'free_y', ncol = 4) + 
#   labs(x = '', y = 'GC average intensity') + 
#   report_theme + d_format +
#   stat_compare_means(position = position_nudge(y = 5)) + stat_pvalue_manual(ptdn_max.gc_cyto.at.dunn, hide.ns = TRUE, label = 'p.adj.rounded', position = position_nudge(y = -2))
# 
# ptdn_max_GC_plot
```
Intensity in axon terminals stays level or decreases with age


Max - soma (cytoplasm) intensity
```{r max_cyto_plot, fig.height = 4, fig.width=16}
max_cyto_plot = ggplot(max.gc_cyto[max.gc_cyto$measure == 'soma',], aes(x = age, y = Mean)) + 
  geom_dotplot(aes(color = age, fill = age), binaxis = "y", stackdir = "center", position = "dodge") + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
  facet_wrap(~cond, scale = 'free_y', ncol = 4) + 
  labs(x = '', y = 'Soma average intensity') + 
  d_format + report_theme + 
  stat_compare_means(position = position_nudge(y = 5))

max_cyto_plot
```
```{r ptdn_max_cyto_plot, fig.height = 4, fig.width = 16}
#ERGIC, SURF4 significant - post-hoc test
soma_test <- ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'soma',] %>% group_by(cond) %>% dplyr::select(Mean, transf)
ptdn_max.gc_cyto.soma.dunn = dunn_test(soma_test, Mean ~ transf, p.adjust.method = 'bonferroni')
ptdn_max.gc_cyto.soma.dunn = add_xy_position(ptdn_max.gc_cyto.soma.dunn, x = 'transf')
ptdn_max.gc_cyto.soma.dunn = add_y_position(ptdn_max.gc_cyto.soma.dunn, step.increase = -0.001)
ptdn_max.gc_cyto.soma.dunn$p.adj.rounded = sapply(ptdn_max.gc_cyto.soma.dunn$p.adj, function(p){round(p, digits = 3)})

ptdn_soma.plotlist = lapply(cond.labels, function(l){ ggplot(ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'soma' & ptdn_max.gc_cyto$cond == l,], aes(x = transf, y = Mean)) + 
  geom_dotplot(aes(colour = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
  labs(x = '', y = 'Soma average intensity') + 
  d_format + report_theme +
  stat_compare_means(position = position_nudge(y = 8)) + stat_pvalue_manual(ptdn_max.gc_cyto.soma.dunn[ptdn_max.gc_cyto.soma.dunn$cond == l,], hide.ns = TRUE, label = 'p.adj.rounded', position = position_nudge(y = 3)) })
names(ptdn_soma.plotlist) = cond.labels

# ptdn_max_cyto_plot = ggplot(ptdn_max.gc_cyto[ptdn_max.gc_cyto$measure == 'soma',], aes(x = transf, y = Mean)) + 
#   geom_dotplot(aes(colour = transf, fill = transf), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 1) + 
#   geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
#   facet_wrap(~cond, scales = 'free_y', ncol = 4) + 
#   labs(x = '', y = 'Soma average intensity') + 
#   d_format + report_theme +
#   stat_compare_means(position = position_nudge(y = 8)) + stat_pvalue_manual(ptdn_max.gc_cyto.soma.dunn, hide.ns = TRUE, label = 'p.adj.rounded', position = position_nudge(y = 3))
# 
# ptdn_max_cyto_plot
```





```{r i3_max_ratio_plot}
i3_max_ratio_plot = ggplot(i3_max.gc_cyto.ratio, aes(x = cond, y = ratio_mean, group = cond)) + 
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge") + 
  labs(x = '', y = 'GC to soma intensity ratio') +
  d_format + report_theme

i3_max_ratio_plot


```


# FULL FIGURES

```{r CNC_vs_i3_ratio_full, fig.height = 10, fig.width=16, fig.path="../figures/full/"}

i3.BCAP31 = image_as_ggplot(read.bitmap('../images/microscopy/i3/i3-BCAP31.png'))
i3.SURF4 = image_as_ggplot(read.bitmap('../images/microscopy/i3/i3-SURF4.png'))
i3.ERGIC53 = image_as_ggplot(read.bitmap('../images/microscopy/i3/i3-ERGIC53.png'))
i3.SLC38A1 = image_as_ggplot(read.bitmap('../images/microscopy/i3/i3-SLC38A1.png'))


CNC_i3_max_ratio_plot = ggplot(rbind(i3_max.gc_cyto.ratio, max.gc_cyto.ratio[max.gc_cyto.ratio$age == 'DIV3',]), aes(x = cell_type, y = ratio_mean)) + 
  geom_dotplot(aes(fill = cell_type, colour = cell_type), binaxis = "y", stackdir = "center", position = "dodge", dotsize = 0.7) +
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = position_dodge(width = 0.9), width = 0.5) +
  facet_wrap(~cond, ncol = 4) + 
  labs(x = '', y = 'Axon terminal:soma intensity ratio') +
  d_format + report_theme +
  stat_compare_means(position = position_nudge(y = 0.1))

i3.layout = 'AAAA
              BCDE'

CNC_i3_max_ratio_plot +
  i3.BCAP31 + i3.SURF4 + i3.ERGIC53 + i3.SLC38A1 +
  plot_annotation(tag_levels = 'A') + plot_layout(design = i3.layout)
```







```{r dev_changes_ratio_full_figure, fig.width=16, fig.height=16, fig.path = "../figures/full/"}
BCAP31.DIV3 = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/BCAP31-DIV3.png'))
SURF4.DIV3 = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SURF4-DIV3.png'))
ERGIC53.DIV3 = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/ERGIC53-DIV3.png'))
SLC38A1.DIV3 = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SLC38A1-DIV3.png'))

BCAP31.DIV15_soma = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/BCAP31-DIV15_soma.png'))
SURF4.DIV15_soma = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SURF4-DIV15_soma.png'))
ERGIC53.DIV15_soma = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/ERGIC53-DIV15_soma.png'))
SLC38A1.DIV15_soma = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SLC38A1-DIV15_soma.png'))

BCAP31.DIV15_GC = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/BCAP31-DIV15_GC.png'))
SURF4.DIV15_GC = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SURF4-DIV15_GC.png'))
ERGIC53.DIV15_GC = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/ERGIC53-DIV15_GC.png'))
SLC38A1.DIV15_GC = image_as_ggplot(read.bitmap('../images/microscopy/dev_changes/SLC38A1-DIV15_GC.png'))

layout = 'AAAA
          BCDE
          FGHI
          JKLM'

max_ratio_plot + 
  BCAP31.DIV3 + SURF4.DIV3 + ERGIC53.DIV3 + SLC38A1.DIV3 +
  BCAP31.DIV15_soma + SURF4.DIV15_soma + ERGIC53.DIV15_soma + SLC38A1.DIV15_soma +
  BCAP31.DIV15_GC + SURF4.DIV15_GC + ERGIC53.DIV15_GC + SLC38A1.DIV15_GC +
  plot_annotation(tag_levels = 'A') + plot_layout(design = layout)
```

```{r protrudin_images}
BCAP31.GFP.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_GFP_soma.png'))
BCAP31.GFP.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_GFP_GC.png'))
BCAP31.WT.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_WT_soma.png'))
BCAP31.WT.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_WT_GC.png'))
BCAP31.Mut2.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_Mut2_soma.png'))
BCAP31.Mut2.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/BCAP31_Mut2_GC.png'))

SURF4.GFP.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_GFP_soma.png'))
SURF4.GFP.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_GFP_GC.png'))
SURF4.WT.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_WT_soma.png'))
SURF4.WT.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_WT_GC.png'))
SURF4.Mut2.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_Mut2_soma.png'))
SURF4.Mut2.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SURF4_Mut2_GC.png'))

ERGIC53.GFP.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_GFP_soma.png'))
ERGIC53.GFP.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_GFP_GC.png'))
ERGIC53.WT.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_WT_soma.png'))
ERGIC53.WT.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_WT_GC.png'))
ERGIC53.Mut2.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_Mut2_soma.png'))
ERGIC53.Mut2.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/ERGIC53_Mut2_GC.png'))

SLC38A1.GFP.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_GFP_soma.png'))
SLC38A1.GFP.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_GFP_GC.png'))
SLC38A1.WT.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_WT_soma.png'))
SLC38A1.WT.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_WT_GC.png'))
SLC38A1.Mut2.soma = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_Mut2_soma.png'))
SLC38A1.Mut2.GC = image_as_ggplot(read.bitmap('../images/microscopy/protrudin_staining/SLC38A1_Mut2_GC.png'))

# layout = 'AAAA
#           BCDE
#           FGHI
#           JKLM
#           NOPQ
#           RSTU
#           VWXY'
#   
# ptdn_max_ratio_plot + 
#   BCAP31.GFP.soma + SURF4.GFP.soma + ERGIC53.GFP.soma + SLC38A1.GFP.soma +
#   BCAP31.GFP.GC + SURF4.GFP.GC + ERGIC53.GFP.GC + SLC38A1.GFP.GC +
#   BCAP31.WT.soma + SURF4.WT.soma + ERGIC53.WT.soma + SLC38A1.WT.soma +
#   BCAP31.WT.GC + SURF4.WT.GC + ERGIC53.WT.GC + SLC38A1.WT.GC +
#   BCAP31.Mut2.soma + SURF4.Mut2.soma + ERGIC53.Mut2.soma + SLC38A1.Mut2.soma +
#   BCAP31.Mut2.GC + SURF4.Mut2.GC + ERGIC53.Mut2.GC + SLC38A1.Mut2.GC + 
#   plot_annotation(tag_levels = 'A') + plot_layout(design = layout)
```

```{r protrudin_BCAP31_full, fig.width = 16, fig.height = 16, fig.path = "../figures/full/"}
BCAP31.layout = 'ABC
                  DEF
                  GHI'


BCAP31.GFP.soma + BCAP31.WT.soma + BCAP31.Mut2.soma + 
  BCAP31.GFP.GC + BCAP31.WT.GC + BCAP31.Mut2.GC +
  ptdn_ratio.plotlist[['BCAP31']] + ptdn_soma.plotlist[['BCAP31']] + ptdn_GC.plotlist[['BCAP31']] + 
  plot_annotation(tag_levels = 'A') + plot_layout(design = BCAP31.layout)
```

```{r protrudin_SURF4_full, fig.width = 16, fig.height = 16, fig.path = "../figures/full/"}
SURF4.layout = 'ABC
                  DEF
                  GHI'


SURF4.GFP.soma + SURF4.WT.soma + SURF4.Mut2.soma + 
  SURF4.GFP.GC + SURF4.WT.GC + SURF4.Mut2.GC +
  ptdn_ratio.plotlist[['SURF4']] + ptdn_soma.plotlist[['SURF4']] + ptdn_GC.plotlist[['SURF4']] + 
  plot_annotation(tag_levels = 'A') + plot_layout(design = SURF4.layout)
```

```{r protrudin_ERGIC53_full, fig.width = 16, fig.height = 16, fig.path = "../figures/full/"}
ERGIC53.layout = 'ABC
                  DEF
                  GHI'


ERGIC53.GFP.soma + ERGIC53.WT.soma + ERGIC53.Mut2.soma + 
  ERGIC53.GFP.GC + ERGIC53.WT.GC + ERGIC53.Mut2.GC +
  ptdn_ratio.plotlist[['ERGIC53']] + ptdn_soma.plotlist[['ERGIC53']] + ptdn_GC.plotlist[['ERGIC53']] + 
  plot_annotation(tag_levels = 'A') + plot_layout(design = ERGIC53.layout)
```

```{r protrudin_SLC38A1_full, fig.width = 16, fig.height = 16, fig.path = "../figures/full/"}
SLC38A1.layout = 'ABC
                  DEF
                  GHI'


SLC38A1.GFP.soma + SLC38A1.WT.soma + SLC38A1.Mut2.soma + 
  SLC38A1.GFP.GC + SLC38A1.WT.GC + SLC38A1.Mut2.GC +
  ptdn_ratio.plotlist[['SLC38A1']] + ptdn_soma.plotlist[['SLC38A1']] + ptdn_GC.plotlist[['SLC38A1']] + 
  plot_annotation(tag_levels = 'A') + plot_layout(design = SLC38A1.layout)
```

