---
title: "HeLa screen"
output: pdf_document
---

```{r HeLa_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dev = 'png')
knitr::opts_chunk$set(fig.path = "../figures/")

source(here::here('./style/thesis_setup.R'))

library(here)
library(readbitmap)
library(reshape2)
library(patchwork)
```

```{r HeLa_read_in_images}
SURF4 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/SURF4_grid.png")))
SEC31A = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/SEC31A_grid.png")))
ERGIC53 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/ERGIC53_grid.png")))
ERGIC53_zoom = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/ERGIC53_zoom.png")))
MIA3 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/MIA3_grid.png")))
BCAP31 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/BCAP31_grid.png")))
  
ACSL3 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/ACSL3_grid.png")))
BODIPYceramide = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/C5-ceramide_grid.png")))
GS28 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/GS28_grid.png")))
GLG1 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/GLG1_grid.png")))
USO1 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/USO1_grid.png")))
  
LC3 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/LC3_grid.png")))
SLC38A1 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/SLC38A1_grid.png")))
Rab11 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/RAB11_grid.png")))
LAMP1 = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/LAMP1_grid.png")))
mTOR = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/mTOR_grid.png")))

```


```{r HeLa_screen_grid, fig.width = 16, fig.height = 26.6, eval = FALSE}
layout = 'AFK
          BGL
          CHM
          DIN
          EJO'

SURF4 + SEC31A + ERGIC53 + MIA3 + BCAP31 + ACSL3 + BODIPYceramide + GS28 + GLG1 + USO1 + LC3 + SLC38A1 + Rab11 + LAMP1 + mTOR +
  plot_layout(design = layout) & plot_annotation(tag_levels = 'A')
```

```{r ERES_grid, fig.width=16, fig.height=16}
ERES_grid = BCAP31 + SURF4 + MIA3 + SEC31A + plot_annotation(tag_levels = 'A') + plot_layout(nrow = 2)
```

```{r Golgi_grid, fig.width=16, fig.height=16}
Golgi_grid = ERGIC53 + GS28 + GLG1 + USO1 + plot_annotation(tag_levels = 'A') + plot_layout(nrow = 2)
```

```{r ERGIC53_extra, fig.width=16, fig.height=4}
ERGIC53_profile.csv = read.csv(here("data/intensity_profiles/HeLa14_ERGIC53_WT3_zoom.tif_profile.csv"))
ERGIC53_profile.csv.normalised = data.frame(X = ERGIC53_profile.csv$X,
                                             ch1 = ERGIC53_profile.csv$Value_ch1/max(ERGIC53_profile.csv$Value_ch1),
                                             ch2 = ERGIC53_profile.csv$Value_ch2/max(ERGIC53_profile.csv$Value_ch2))
ERGIC53_profile.melt = melt(ERGIC53_profile.csv.normalised, measure.vars = c('ch1', 'ch2'))
ERGIC53.pixelsize = 0.2273 #microns, from TIF metadata
ERGIC53_profile.melt$distance = (ERGIC53_profile.melt$X - 1)*ERGIC53.pixelsize

ERGIC53_profile = ggplot(ERGIC53_profile.melt, aes(x = distance, y = value, group = variable)) + 
  geom_area(aes(fill = variable), alpha = 0.25, position = 'dodge') +
  geom_line(aes(colour = variable), size = 2) +
  labs(y = 'Normalised fluorescence intensity', x = paste0('Distance (', '\U03BC', 'm)')) +
  d_format + report_theme
```

```{r Golgi_grid_extended, fig.width = 16, fig.height = 22}

Golgi_layout = 'AAAA
                AAAA
                AAAA
                AAAA
                BBBB'

Golgi_extended = Golgi_grid/ (ERGIC53_zoom + ERGIC53_profile + plot_layout(design = 'AAAB')) + plot_annotation(tag_levels = 'A') + plot_layout(design = Golgi_layout)

```

```{r misc_grid, fig.width=16, fig.height=16}
misc_grid = LAMP1 + mTOR + ACSL3 + SLC38A1 + plot_annotation(tag_levels = 'A') + plot_layout(nrow = 2)
```


```{r HeLa_ceramide_full_figure, fig.width = 16, fig.height = 8}
ceramide_profile.csv = read.csv(here("data/intensity_profiles/HeLa14_ceramide_WT3.tif_profile.csv"))
ceramide_profile.csv.normalised = data.frame(X = ceramide_profile.csv$X,
                                             ch1 = ceramide_profile.csv$Value_ch1/max(ceramide_profile.csv$Value_ch1),
                                             ch2 = ceramide_profile.csv$Value_ch2/max(ceramide_profile.csv$Value_ch2))
ceramide_profile.melt = melt(ceramide_profile.csv.normalised, measure.vars = c('ch1', 'ch2'))

ceramide.pixelsize = 0.2273 #microns, from TIF metadata
ceramide_profile.melt$distance = (ceramide_profile.melt$X - 1)*ceramide.pixelsize

ceramide_profile = ggplot(ceramide_profile.melt, aes(x = distance, y = value, group = variable)) + 
  geom_area(aes(fill = variable), alpha = 0.25, position = 'dodge') +
  geom_line(aes(colour = variable), size = 2) +
  labs(y = 'Normalised fluorescence intensity', x = paste0('Distance (', '\U03BC', 'm)')) +
  scale_x_continuous(breaks = waiver(), n.breaks = 6) + 
  d_format + report_theme

grid_panel = image_as_ggplot(read.bitmap(here("images/microscopy/HeLa_montages/C5-ceramide_WT_inset_grid.png")))

ceramide_grid = grid_panel + ceramide_profile + plot_annotation(tag_level = 'A')

ceramide_grid
```

