---
title: "Protrudin_autophagy_analysis"
output: pdf_document
---

```{r LC3_setup}
knitr::opts_chunk$set(echo = FALSE, dev = 'png')
knitr::opts_chunk$set(fig.path = "../figures/")

source(here::here('./style/thesis_setup.R'))

library(dplyr)
library(ggplot2)
library(readbitmap)
library(here)
library(patchwork)
```

Load in count CSVs
```{r}
CNC100 = read.csv(here('data/LC3_analysis/CNC100_LC3_dist.csv'))
CNC101 = read.csv(here('data/LC3_analysis/CNC101_LC3_dist.csv'))

CNC100$expt = rep('CNC100', nrow(CNC100))
CNC101$expt = rep('CNC101', nrow(CNC101))

LC3_dist.df = rbind(CNC100, CNC101)
```

Combine experiments
```{r}
LC3_dist.simple = LC3_dist.df %>% group_by(condition, distribution) %>% summarise(count = sum(number))
LC3_dist.simple$condition = factor(LC3_dist.simple$condition, levels = c('GFP', 'WT', 'Mut2'), labels = c('Control', 'WT', 'Active'))

```

Plot

```{r LC3_dist_plot}
LC3_neuron_plot = ggplot(LC3_dist.simple, aes(x = condition, fill = distribution, y = count)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  labs(y = 'Number of cells', x = '', fill = 'LC3 distribution') + 
  report_theme + scale_fill_viridis_d() + theme (legend.position = 'right')

LC3_neuron_plot
```

```{r LC3_profile_plot}
LC3.prof = read.csv(here('data/intensity_profiles/HeLa7_LC3_WT2_Stack_profile.csv'))
LC3.prof.norm = data.frame(X = LC3.prof$X,
                       ch1 = LC3.prof$Value_ch1/max(LC3.prof$Value_ch1),
                       ch2 = LC3.prof$Value_ch2/max(LC3.prof$Value_ch2))
LC3.prof.melt = reshape2::melt(LC3.prof.norm, measure.vars = c('ch1', 'ch2'))

LC3.pixelsize = 0.2273 #size in microns, from TIF metadata - TODO grab from image directly?
LC3.prof.melt$distance = (LC3.prof.melt$X - 1)*LC3.pixelsize#starting @ 0.0

LC3_profile_plot = ggplot(LC3.prof.melt, aes(x = distance, y = value, group = variable)) + 
  geom_area(aes(fill = variable), alpha = 0.25, position = 'dodge') + geom_line(aes(colour = variable), size = 2) + 
  labs(y = 'Normalised fluorescence intensity', x = paste0('Distance (', '\U03BC', 'm)')) +
  d_format + report_theme

LC3_profile_plot 

```

```{r neuron_examples}
LC3_neuro = image_as_ggplot(read.bitmap(here('images/microscopy/LC3/LC3_neuron_examples.png')))
```
```{r HeLa_grid}
LC3_grid = image_as_ggplot(read.bitmap(here('images/microscopy/HeLa_montages/LC3_WT_inset_grid.png')))
LC3_GFP = image_as_ggplot(read.bitmap(here('images/microscopy/HeLa_montages/LC3_GFP_montage_spaced.png')))
```
```{r LC3_protrusion}
LC3_protrusion = image_as_ggplot(read.bitmap(here('images/microscopy/HeLa_montages/LC3_WT_protrusion_vertical.png')))
```

```{r LC3_full, fig.width=16, fig.height=18}
LC3.layout = 'AAAAAABB
              AAAAAABB
              AAAAAACC
              AAAAAACC
              AAAAAACC
              DDDDDDCC
              DDDDDDCC
              EEEEEEFG
              EEEEEEFG'

LC3_full_plot = LC3_grid + LC3_profile_plot + LC3_protrusion + LC3_GFP + LC3_neuro + LC3_neuron_plot + guide_area() + plot_annotation(tag_levels = 'A') + plot_layout(design = LC3.layout, guides = 'collect')

LC3_full_plot
```