---
title: "Golgi satellite puncta counts"
output: pdf_document
---
```{r GS_puncta_setup}
knitr::opts_chunk$set(echo = TRUE, dev = 'png', message = FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80))
knitr::opts_chunk$set(fig.path = "../figures/")

source('../style/thesis_setup.R')

library(ggplot2)
library(ggpubr)
library(readbitmap)
library(here)
library(patchwork)
```

Read in St3Gal5 puncta count CSV
```{r}
# puncta = read.csv('C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\CNC114-116_Ptdn-St3Gal5_puncta_TIFs\\max_projections\\GFP\ -\ puncta\\puncta_counts\\counts.csv')
puncta = read.csv(here('data/puncta_counts/counts.csv'))
fileparse = lapply(puncta$File, function(f){ strsplit(f, "_") })

puncta$expt = sapply(1:nrow(puncta), function(i){fileparse[[i]][[1]][1]})
puncta$cond = sapply(1:nrow(puncta), function(i){fileparse[[i]][[1]][2]})
puncta$cell = sapply(1:nrow(puncta), function(i){fileparse[[i]][[1]][3]})

puncta$cond = factor(puncta$cond, levels = c('mCh', 'WT', 'Mut2'), labels = c('Control', 'WT', 'Active'))

puncta$norm_count = sapply(1:nrow(puncta), function(i){ puncta$Count[i]/puncta$ROI_length[i] })
```


```{r GS_count_plot}
GS_count_plot = ggplot(puncta, aes(x = cond, y = norm_count)) + 
  geom_dotplot(aes(fill = cond, colour = cond), binaxis = "y", stackdir = "center", position = "dodge") + 
  geom_boxplot(fill = NA, colour = 'black', outlier.color = NA, position = "dodge", width = 0.5) + 
  labs(x = '', y = 'Number of puncta/length of axon segment') + 
  stat_compare_means() + 
  d_format + report_theme
```


```{r puncta_intensities}
# puncta_dir = 'C:\\Users\\fl299\\PhD\\Data\\Mine\\Confocal\\CNC114-116_Ptdn-St3Gal5_puncta_TIFs\\max_projections\\GFP\ -\ puncta\\puncta_counts'
puncta_dir = '../data/puncta_counts/'
puncta_files = list.files(puncta_dir)
puncta_files = puncta_files[which(!puncta_files %in% c('counts.csv', 'desktop.ini'))]

intensities = do.call(rbind, lapply(puncta_files, function(f){ 
                                                    print(f)
                                                    parse = strsplit(f, "_")
                                                    csv = read.csv(paste0(puncta_dir, "\\", f))
                                                    int = csv$Max
                                                    
                                                    df = data.frame(
                                                      expt = rep(parse[[1]][1], length(int)),
                                                      cond = rep(parse[[1]][2], length(int)),
                                                      cell = rep(parse[[1]][3], length(int)),
                                                      intensity = int
                                                    )
                                                    print(nrow(df))
                                                    return(df)
                                                  }))
intensities$cond = factor(intensities$cond, levels = c('mCh', 'WT', 'Mut2'), labels = c('Control', 'WT', 'Active'))
```

```{r GS_intensity_plot}
GS_intensity_plot = ggplot(intensities, aes(x = cond, y = intensity, colour = cond)) + 
  geom_violin() +   geom_boxplot(fill = NA, outlier.shape = NA, position = "dodge", width = 0.2) + 
  labs(x = '', y = 'Point intensity') +
  stat_compare_means() + 
  d_format + report_theme
```

```{r GS_puncta_full, fig.width = 16, fig.height = 16}
puncta_image = image_as_ggplot(read.bitmap(here("images/microscopy/St3Gal5/Puncta_example_116Mut26_annotated.png")))
puncta_inset = image_as_ggplot(read.bitmap(here("images/microscopy/St3Gal5/Puncta_example_116Mut26_annotated_inset.png")))

GS_puncta_layout = 'AABB
                    AABB
                    AABB
                    CCDD'
GS_puncta_full_figure = puncta_image + puncta_inset + GS_count_plot + GS_intensity_plot + plot_annotation(tag_levels = 'A') + plot_layout(design = GS_puncta_layout)

GS_puncta_full_figure
```