---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

# Discussion {.unnumbered #DISCUSSION}

```{=latex}
\markboth{DISCUSSION}{}
\setcounter{chapter}{4}
\setcounter{section}{0}
\setcounter{figure}{0}
```

## Results

### Protrudin's role in axonal transport

Perhaps the most surprising finding of this project has been that protrudin overexpression has little if any effect on lysosome or late endosome transport in cortical neurons.  Initially, this seems to conflict with previous work in other cell types, which suggest that protrudin has a strong effect on late endosome transport and positioning, [@raiborgRepeatedEREndosome2015; @hongPtdIns3PControlsMTORC12017].  However, this is in fact consistent with the mechanism proposed in those studies,  which identifies FYCO1 as the actual adaptor between late endosomes and kinesin.  As numerous RNAseq data sets show that there is extremely little FYCO1 in CNS neurons (figure \@ref(fig:FYCO1-RNAseq-full-figure)), it seems likely that this mechanism is not active in these neurons.  Instead, anterograde lysosome/late endosome transport in axons is probably mediated primarily by the BORC/ARL8B/SKIP mechanism, as suggested by Farias et al. [@fariasBORCKinesin1Ensemble2017].

This apparent cell-type variability in protrudin function has important implications for its development as a regenerative gene therapy.  Further work will be required to characterise the effects of protrudin overexpression on different cell types and tissues, and to ensure that therapeutic vectors target protrudin expression to the correct cellular population.

In addition, this finding raises interesting questions about the role of FYCO1 in regeneration.  As FYCO1 appears to facilitate protrudin's role in cellular outgrowth, but is largely absent from mature CNS neurons, it is possible that FYCO1 expression is correlated with the intrinsic regenerative capacity of different cell types.  Investigating this further might shed more light on why most CNS neurons are such poor regenerators, and identify novel targets to promote regeneration.

The effect of active protrudin on Golgi satellite transport (figure \@ref(fig:ST3GAL5-full-figure)), in contrast with late endosomes (in particular those marked by RAB7, as shown in figure \@ref(fig:RAB7-full-figure)), shows that protrudin has specific and distinct effects on different organelles in the axon.  This is further confirmed by Petrova et al., which showed that both wild type and active protrudin increased the number of RAB11 recycling endosomes in the distal axon, an effect not seen with any of the transport markers used in this thesis [@petrovaProtrudinFunctionsEndoplasmic2020].  Based on these results, we can confidently say that protrudin does not indiscriminately increase axonal transport or localisation, but rather specifically mediates the organisation and behaviour of particular organelles through distinct mechanisms.


### Protrudin's role in local translation

Given its effect on ERGIC localisation (figure \@ref(fig:ERGIC53-plot)) and the dynamics of Golgi satellite transport (figure \@ref(fig:ST3GAL5-full-figure)), it appears that protrudin overexpression — particularly active protrudin — has a significant effect on the local secretory machinery in axons.  Considering the importance of local translation on axon function and growth, as discussed previously, it is easy to see how this might contribute to both protrudin's neuroprotective and regenerative effects.  Additionally, recent work has indicated a direct link between the level of local translation in axons and their regenerative capacity, supporting the idea that protrudin could act by coordinating machinery for local protein synthesis and processing [@vanerpAgerelatedLossAxonal2021].

This is worth considering in the context of the previous finding that protrudin increases the amount of RAB11 recycling endosomes in the distal axon [@petrovaProtrudinFunctionsEndoplasmic2020].  Bowen et al. showed that recycling endosomes can play a role in the secretion of locally translated proteins in dendrites, either through Golgi satellites or entirely bypassing Golgi-related compartments [@bowenGolgiindependentSecretoryTrafficking2017].  Therefore, it is possible that these endosomes also comprise part of the secretory machinery in axons, in addition to ERGIC and Golgi satellites. 

Further work will be required to identify the molecular mechanisms at play in this process, and whether it is a result of direct protrudin interactions or is downstream of other cellular effects.  This may well vary for each component of the secretory pathway — for example, protrudin can bind to RAB11 directly to facilitate recycling endosome transport, but no such interactions have yet been identified for ERGIC or Golgi satellites.  However, the presence of numerous Golgi-related proteins in protrudin interactomes (figure \@ref(fig:proteomics-full-figure)) strongly suggests a direct involvement in ER-Golgi interactions.


## Future directions

While this project has provided some answers to how protrudin can promote survival and regeneration, it also raises new questions which should be addressed in future studies.  In addition to the follow-up experiments mentioned above, several other systems should be investigated in the context of protrudin overexpression to understand their impact on its neuroprotective and regenerative effects.

### Autophagy

Protrudin's effects on LC3 localisation, both in HeLa cells and cortical neurons (figure \@ref(fig:LC3-full-figure)), suggest an active role in regulating autophagy.  The preliminary results demonstrated in this project suggest that protrudin may increase autophagy or autophagosome biogenesis.  However, Hong et al. actually found the opposite — protrudin *depletion* promoted autophagy initiation in cultured epithelial cells [@hongPtdIns3PControlsMTORC12017].  

It is very likely that this effect varies by cell type, similar to the effect on lysosomal transport, and for the same reason — FYCO1 acts as an adaptor for autophagosome transport, and is involved in autophagosome maturation [@pankivFYCO12010; @olsvikFYCO1ContainsCterminally2015].  However, there are other potential mechanisms through which protrudin could affect neuronal autophagy in the absence of FYCO1, as both ER contact sites and RAB11 endosomes have been implicated in early autophagosome formation [@bieberSituStructuralAnalysis2022; @puriRAB11APositiveCompartmentPrimary2018]

With this in mind, it would be worthwhile to examine further what effect protrudin overexpression has on autophagy, particularly in CNS neurons.  Given the abundance of literature linking autophagy to neuronal survival [reviewed in @overhoffMechanismsNeuronalSurvival2021], this may well represent another pathway through which protrudin acts, particularly in a neuroprotective role.

### Lipids {#discussion-lipids}

Numerous results throughout this thesis suggest a link between protrudin and lipid metabolism.  The gene ontology analysis in section \@ref(GO-analysis) highlighted a number of protrudin interactions with genes involved in lipid metabolism.  The unusual localisation of BODIPY C~5~ ceramide in HeLa cells expressing protrudin also supports the idea of an effect on lipid pathways in the cell (figure \@ref(fig:ceramide-full-figure)).  Furthermore, the enzyme ST3GAL5, used in this thesis as a marker for Golgi satellites, is an enzyme important for the production of gangliosides, glycolipids that form a key component of neuronal cell membranes and are important for axonal growth and maintenance [reviewed in @sipioneGangliosidesBrainPhysiology2020].  Given protrudin's effect on the transport of these organelles, this could suggest a change to how lipids are metabolised and processed in the axon.  Ewan et al. identified changes in lipid metabolism as a key factor distinguishing PNS from CNS axon regeneration, suggesting that protrudin could potentially promote regeneration through these pathways [@ewanAscendingDorsalColumn2021].

In a collaborative project with the Williams lab at the Karolinska Institutet, mice were injected intravitreally with AAV2 encoding the CAG protrudin constructs used in this thesis.  Lipid mass spectroscopy of these mice's optic nerves showed that either WT or active protrudin expression decreased the level of ceramides while increasing hexosylceramides, pointing to an effect on sphingolipid synthesis pathways (data not shown).  Further work is ongoing in this area to understand how protrudin overexpression influences lipid pathways in the cell, and what effect this has on neuronal survival and regeneration.

### Mitochondria

Previous work has suggested that protrudin may play a role at ER-mitochondrial contact sites [@elbaz-alonPDZD8InteractsProtrudin2020; @chingQuantifyingInterorganelleMembrane2021], although it is not yet clear what effects this may have on the cell.  Preliminary EM data from another collaboration with the Williams lab show some unusually long mitochondria in the optic nerves of mice expressing active protrudin, which were not observed with a GFP control (data not shown).  Work is ongoing to confirm this result and examine potential mechanisms.

## Implications for glaucoma therapy

Given that the initial aim of this project was to develop protrudin into a gene therapy for glaucoma, it is worth considering these findings in that context.  While we were unable to perform *in vivo* experiments during this project, the results presented in this thesis still have important implications for future work in this area.

As discussed above, the lack of any apparent effect of protrudin expression on axonal lysosome and late endosome transport, due to the absence of FYCO1, indicates that protrudin is likely to have very different effects on different cell types.  While initial *in vivo* experiments with protrudin have shown very positive results, with significantly improved retinal ganglion cell survival and regeneration after an optic nerve crush, care should be taken to look out for any expression outside of this target cell population, and to characterise the effect of protrudin overexpression in glial and epithelial cell lines [@petrovaProtrudinFunctionsEndoplasmic2020].  

Furthermore, the results presented in chapters 2 and 3 of this thesis identify a new cellular system — the local secretory pathway — through which protrudin might act to promote survival and regeneration in CNS neurons.  Other components of this pathway, particularly any that might regulate localisation or inter-organelle interactions, should therefore be examined for potential neuroprotective and regenerative benefits.  While it may be possible to identify entirely new gene therapy candidates in this way, it might also be possible to identify proteins that can act synergistically with protrudin for improved therapeutic effects.  

## Conclusion — A unifying site of action

The results of this project, taken in combination with previous work, suggests that protrudin is coordinating an 'axon trafficking centre', increasing ER tubules, ERGIC, and recycling endosomes — all key components of the local secretory pathway — in the distal axon.  Through the actions of the virtuous cycle, this arrangement of organelles can promote integrin delivery, facilitate local protein translation and processing, and encourage growth-promoting signalling cascades to increase survival and axonal regeneration.

Whether this coordination occurs through direct interactions or downstream of other cellular effects is unclear, but it seems likely that this is a contributing factor to protrudin's effectiveness as a CNS therapy.  Future work in this area should be focused on the structure and nature of interactions between pathway components (ER, ERGIC, Golgi satellites, and endosomes), how they are recruited to sites of axonal injury or degeneration, and whether they are directly associated with regenerative ability.  
